syslinux: no ui, no escape
This one was suggested by enp@ for industrial use where
some extra protection for the boot process might be quite
desirable.

If no syslinux ui was specified (the stock configuration paths
ensure there is one) or if it was set to "none" explicitly,
then there's no boot: prompt (let alone any menu).

If there's a need to ensure that the boot process is not
interruptable by Ctrl/Shift/Caps Lock/Scroll Lock.

diff --git a/features.in/syslinux/stage1/scripts.d/01-syslinux b/features.in/syslinux/stage1/scripts.d/01-syslinux
--- a/features.in/syslinux/stage1/scripts.d/01-syslinux
+++ b/features.in/syslinux/stage1/scripts.d/01-syslinux
@@ -3,6 +3,7 @@
 # copy modules; see also ../../generate.mk
 
 MODDIR="/usr/lib/syslinux"
+CFG="$GLOBAL_BOOTLOADER.cfg"
 
 mkdir -p "$WORKDIR/syslinux"
 cd "$WORKDIR/syslinux"
@@ -30,7 +31,18 @@ if [ -n "$SYSLINUX_MODULES" ]; then
 fi
 
 # number ordering sponsored by shell's pathname expansion
-grep -hv '^#' .in/[0-9][0-9]*.cfg > "$GLOBAL_BOOTLOADER.cfg"
+grep -hv '^#' .in/[0-9][0-9]*.cfg > "$CFG"
+
+# there should be either DEFAULT or UI directive there
+if ! egrep -i '^(default|ui)' "$CFG"; then
+	DEFAULT="$(grep -i '^label ' "$CFG" | head -1 | cut -f2 -d' ')"
+	if [ -n "$DEFAULT" ]; then
+		echo "default $DEFAULT" >> "$CFG"
+	else
+		echo "error: no DEFAULT or UI directive and cannot guess" >&2
+		exit 1
+	fi
+fi
 
 # snippets are not going into the actual image
 if [ "$DEBUG" != 2 ]; then rm -r .in/; fi
