QUICKSTART, mktmpdir, build.mk: hasher's /proc
Either /etc/hasher-priv/system or /etc/hasher-priv/user.d/$USER
must contain at least "allowed_mountpoints=/proc" for mkimage
to work for mkimage-profiles; thanks Daniil Golovanov for
providing feedback indicating the lack of the corresponding
checks.

diff --git a/bin/mktmpdir b/bin/mktmpdir
--- a/bin/mktmpdir
+++ b/bin/mktmpdir
@@ -6,6 +6,14 @@
 DIRS="$TMP $TMPDIR $HOME/hasher /tmp /var/tmp .."
 MINSIZE=262144		# face control criterion
 
+# mkimage needs /proc among those, be clear about that
+check_allowed_mountpoints()
+{
+	grep -wqs "^allowed_mountpoints=[^#]*/proc" \
+		/etc/hasher-priv/system \
+		`/usr/libexec/hasher-priv/getconf.sh`
+}
+
 # poor man's SourceIfExists()
 try_source() { [ -f "$1" ] && . "$1"; }
 
@@ -59,6 +67,12 @@ choose_tmpdir() {
 }
 
 # bringing it all together
+if ! check_allowed_mountpoints; then
+	echo "error: hasher's allowed_mountpoints do not include /proc;"
+	echo "please check hasher docs and /etc/hasher-priv/system"
+	exit 1
+fi >&2
+
 TMPDIRS="`contemplate_dirs $DIRS`"
 if [ -z "$TMPDIRS" ]; then
 	echo "error: no suitable directories found;"
