stage2: no kernels no go
The flexible KFLAVOURS handling has a downside:
if no packages match the regexp it's silently OK
until too late, and the error is incomprehensible.
Let's fix the latter at least.

diff --git a/sub.in/stage2/image-scripts.d/98-depmod b/sub.in/stage2/image-scripts.d/98-depmod
--- a/sub.in/stage2/image-scripts.d/98-depmod
+++ b/sub.in/stage2/image-scripts.d/98-depmod
@@ -4,5 +4,9 @@
 
 cd /lib/modules
 for i in *.*; do
+	if [ "$i" = "*.*" ]; then
+		echo "** error: no valid KFLAVOURS installed, bailing out" >&2
+		exit 1
+	fi
 	depmod -a -F /boot/System.map-$i $i
 done
