initial vm-{net,ssh} features
A virtual machine isn't very useful if there are no means
to access it; let's bring up the basic networking and provide
root SSH access via pre-existing public key.

As the remote access with known default credentials is roughly
equivalent to just lending one's VMs to anyone with network
access to it, the fallback root password is now exterminated;
you have to provide one (or a long enough random string
if you plan to use keys only, see e.g. apg utility).

diff --git a/features.in/build-vm/image-scripts.d/00root b/features.in/build-vm/image-scripts.d/00root
--- a/features.in/build-vm/image-scripts.d/00root
+++ b/features.in/build-vm/image-scripts.d/00root
@@ -1,7 +1,11 @@
 #!/bin/sh
 
-ROOTPW="${GLOBAL_ROOTPW:-root}"
-
-if type -t chpasswd >&/dev/null; then
-	echo "root:$ROOTPW" | chpasswd
+if [ -n "$GLOBAL_ROOTPW" ]; then
+	if type -t chpasswd >&/dev/null; then
+		echo "root:$GLOBAL_ROOTPW" | chpasswd
+	else
+		echo "** warning: chpasswd binary missing" >&2
+	fi
+else
+	echo "** warning: no root password provided, you're on your own" >&2
 fi
