repo: harden against missing keydir
rpm-4.13 stopped bringing alt-gpgkeys in, and specifying it
explicitly for STAGE1_PACKAGES didn't help somehow; don't presume
/usr/lib/alt-gpgkeys/ existence anyways.

diff --git a/features.in/repo/scripts.d/02-pubring b/features.in/repo/scripts.d/02-pubring
--- a/features.in/repo/scripts.d/02-pubring
+++ b/features.in/repo/scripts.d/02-pubring
@@ -1,4 +1,9 @@
 #!/bin/sh
 # generate current plaintext rpm pubring representation
+KEYDIR="/usr/lib/alt-gpgkeys"
 
-gpg --export --armor --homedir=/usr/lib/alt-gpgkeys >$WORKDIR/RPM-GPG-KEY
+if [ -d "$KEYDIR" ]; then
+	gpg --export --armor --homedir="$KEYDIR" >$WORKDIR/RPM-GPG-KEY
+else
+	echo "** warning: skipping RPM-GPG-KEY generation, $KEYDIR missing" >&2
+fi
