kernel, stage2: rearranged initrd hooks
stage2 has been thinking it's synonymous with propagator
and used to usurp kernel's belongings either; carefully
tear scripts apart so that kernel feature makes sure
initrd gets generated, and stage2 (which is still all
about propagator) cares for its bits.

diff --git a/features.in/kernel/stage1/scripts.d/80-make-initrd b/features.in/kernel/stage1/scripts.d/80-make-initrd
--- a/features.in/kernel/stage1/scripts.d/80-make-initrd
+++ b/features.in/kernel/stage1/scripts.d/80-make-initrd
@@ -1,7 +1,7 @@
 #!/bin/sh -efux
 # NB: /etc/initrd.mk carefully prepared by earlier scripts
 
-verbose() { [ -z "$GLOBAL_VERBOSE" ] || echo "** 80-make-initfs: $@" >&2; }
+fatal() { echo "** error: $@" >&1; exit 1; }
 
 kver="$(rpm -qa 'kernel-image*' \
 	    --qf '%{installtime} %{version}-%{name}-%{release}\n' \
@@ -9,6 +9,9 @@ kver="$(rpm -qa 'kernel-image*' \
 	| tail -n 1 \
 	| cut -f 2 -d ' ' \
 	| sed 's/kernel-image-//')"
+
+[ -n "$kver" ] ||
+	fatal "no kernel version identified"
 
 MAKE_INITRD_OPTS="--no-checks -k $kver"
 MAKE_INITRD_VER="`make-initrd -V \
@@ -19,17 +22,16 @@ if [ "`rpmvercmp "$MAKE_INITRD_VER" "0.7.8"`" != "-1" ]; then
 	MAKE_INITRD_OPTS="$MAKE_INITRD_OPTS --no-depmod"
 fi
 
-[ -z "$GLOBAL_VERBOSE" ] || MAKE_INITRD_OPTS="$MAKE_INITRD_OPTS -v"
+[ -z "$GLOBAL_VERBOSE" ] ||
+	MAKE_INITRD_OPTS="$MAKE_INITRD_OPTS -v"
 
-if make-initrd $MAKE_INITRD_OPTS; then
-	pdir="$(getconf LIBDIR)/propagator"
-	mkdir -p "$pdir"
-	gzip < /boot/initrd-$kver.img > "$pdir"/initfs
-else
-	verbose "make-initrd failed"
-	exit 1
-fi
+make-initrd $MAKE_INITRD_OPTS ||
+	fatal "make-initrd failed"
 
-[ -h /boot/vmlinuz ] || ln -s vmlinuz-$kver /boot/vmlinuz
-[ -h /boot/initrd.img ] || ln -s initrd-$kver.img /boot/initrd.img
+[ -h /boot/vmlinuz ] ||
+	ln -s vmlinuz-$kver /boot/vmlinuz
+
+[ -h /boot/initrd.img ] ||
+	ln -s initrd-$kver.img /boot/initrd.img
+
 :
