live, rescue: fixup 60-apt
There are two different versions of the script with the same
name for different subprofiles, sharing some of the same bugs
over the years, *sigh*.

Shoving those into stage2 would yield online repositories enabled
there too which *might* be wanted but will likely need installer
support (at least some better error handling, the current culprit
with unavailable repositories being apt-pkg's size estimation).

Fixes: d2f892abda0ddc02df482cef87c398906d7c93ff
Fixes: 0f4ee98fa4360dd1caf48f5d38b1e89925a66f1c

diff --git a/features.in/rescue/rescue/image-scripts.d/60-apt b/features.in/rescue/rescue/image-scripts.d/60-apt
--- a/features.in/rescue/rescue/image-scripts.d/60-apt
+++ b/features.in/rescue/rescue/image-scripts.d/60-apt
@@ -1,4 +1,5 @@
 #!/bin/sh
 # enable online repository even more unconditionally
 
-sed -i "s,^#\(rpm .* http.*\),\1," "/etc/apt/sources.list.d/yandex.list" ||	echo "** warning: unable to enable online repos" >&2
+sed -i "s,^#\(rpm .* http.*\),\1," "/etc/apt/sources.list.d/yandex.list" ||
+	echo "** warning: unable to enable online repos" >&2
