35-xdg-user-dirs: cope with missing control
There's no reason to bail out if xdg-user-dirs control
facility is not available within the branch used.

diff --git a/features.in/live/live/image-scripts.d/35-xdg-user-dirs b/features.in/live/live/image-scripts.d/35-xdg-user-dirs
--- a/features.in/live/live/image-scripts.d/35-xdg-user-dirs
+++ b/features.in/live/live/image-scripts.d/35-xdg-user-dirs
@@ -1,4 +1,6 @@
 #!/bin/sh
 # Turn on xdg-user-dirs.
+# NB: not yet available on t6/p6 hence the warning
 
-control xdg-user-dirs enabled
+control xdg-user-dirs enabled ||
+	echo "** warning: control xdg-user-dirs failed" >&2
