features.in: fix some engrish
The proper form is "does not" here.

diff --git a/features.in/live/live/image-scripts.d/60-apt b/features.in/live/live/image-scripts.d/60-apt
--- a/features.in/live/live/image-scripts.d/60-apt
+++ b/features.in/live/live/image-scripts.d/60-apt
@@ -28,7 +28,7 @@ fi
 repo_source="/etc/apt/sources.list.d/$MIRROR.list"
 
 if [ ! -s "$repo_source" ]; then
-	echo "Error: $repo_source is not exist" >&2
+	echo "Error: $repo_source does not exist" >&2
 	exit 1
 fi
 
diff --git a/features.in/repo/install2/image-scripts.d/90-repo-mirror b/features.in/repo/install2/image-scripts.d/90-repo-mirror
--- a/features.in/repo/install2/image-scripts.d/90-repo-mirror
+++ b/features.in/repo/install2/image-scripts.d/90-repo-mirror
@@ -10,7 +10,7 @@ MIRROR="${GLOBAL_REPO#*/}"	# alt, heanet, kiev, yandex, ...
 repo_source="/etc/apt/sources.list.d/$MIRROR.list"
 
 if [ ! -s "$repo_source" ]; then
-	echo "Error: $repo_source is not exist" >&2
+	echo "Error: $repo_source does not exist" >&2
 	exit 1
 fi
 
